dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - libxml2-utils
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: MJPd78371wjFdSG9J5RVx9IEERkEmQ98lgERO4ka30B8xPgPHGcuA6XSktKzaAkeZSWFdrW4xOjt23nk2OWcej+JZ0u3q8VzDzkFvMf4V9M2657PHklB90RHLJjexI4zvRrnSqQaBPuytdOMhPCZ0R/kVqDBH/enlxZbTTTaBojptxqksC4toP25dCOdMI2pY2bODz9vSw1jBL2th6cz6jVkC354/cEMscAzvClVtpewaWwTUPBvtAN4zQ6OWjf/iSbRDAreKXPxgt9sqy1zkZInc1TE8ffavMxWgNOGnlRxQLaYHCTjso/H+gvqQiZ+/FLnVKva8+4bfmGeE/D4Db0IEfNoHvt0zt+OYfY+8fo2rfp6t8GT4Onaiqt4xfwv0g+Qm64rYKV6LrfNAIRYCBLS0xE2luSorFlP+4u2ER7MDwG1BWAdcoBPSzXPbBPgyW9ThCwz22cFyhMrZOii6bXIVUW7B7sR+aS6PeH8uTGSLYVQnQbZERXdb99JsMOP7tc2zCib/Xw2ZjSmHxrb9LdknfSr+0pgJ83He67ARg57bf7PCgePR5QLiRN+jdgwUahnzszBUq+wfSMWCWdPAyl5tgKT34AD67+v5BdYP7IW83FUqK9+TEquonfITjE3Zm/FmPyn8v9prcoe+HbRBKzMRw2p/J7EVQ1CsLMka9c=
install: true
script: bash .travis/travis-build.bash
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    on_error: always
    on_cancel: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - "$HOME/.m2"
